# github Action의 이름
name: helloGithubAction

# 이벤트 리스너라고 보면 됩니다. push외에도 pull_request가 들어갈 수 있고 배열 형태인 만큼, 다중 이벤트를 처리하는 것도 가능합니다. 
on: #[push]
  # 5분 단위로 가능하고, 5가 최소기 때문에 10으로 설정 아래가 10분 단위라는 뜻
  schedule:
    - cron: "*/10 * * * *"
    
# 위의 이벤트가 일어나면 아래의 job이 실행됩니다.
jobs:
  # 작업 단위
  build:
    # 실행되는 OS, window, mac os 도 제공합니다. 자세한 버전은 우측의 documentation 참고하자.
    runs-on: ubuntu-latest
    steps:
    # 다른 사람이 만들어놓은 action import - (github.com/actions/checkout | marketplace)
    - uses: actions/checkout@v2
    - name: 1. 파일 목록 출력
      run: ls -al
    - name: 2. 설치되어 있는 패키지 확인
      run: pip list
    - name: 3. pip 업그래이드
      run: python -m pip install --upgrade pip
    - name: 4. 환경 설정
      run: pip install -r requirements.txt
    - name: 5. 파이썬 실행
      run: python githubactiontest.py
